package view.GUI;


import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.Vector;
import javax.swing.JOptionPane;
import entidades.Aluno;
import org.neodatis.odb.ODB;
import org.neodatis.odb.ODBFactory;
import org.neodatis.odb.Objects;
import org.neodatis.odb.core.query.IQuery;
import org.neodatis.odb.core.query.criteria.Where;
import org.neodatis.odb.impl.core.query.criteria.CriteriaQuery;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vagner
 */
public class GUICadastro extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L;
    URL url = this.getClass().getResource("/arquivos/INSTITUTO_ICON.png");
    Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url); 
    
    /**
     * Creates new form GUICadastro
     */
    public GUICadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abasSistemaCadastro = new javax.swing.JTabbedPane();
        jPanelCadastroDeAluno = new javax.swing.JPanel();
        jLabelNomeCadastro = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelMatriculaCadastro = new javax.swing.JLabel();
        jTextFieldMatricula = new javax.swing.JTextField();
        jLabelEmailCadastro = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jButtonSalvarCadastro = new javax.swing.JButton();
        jButtonLimparCadastro = new javax.swing.JButton();
        imagemIfpbCadastro = new javax.swing.JLabel();
        jPanelConsulta = new javax.swing.JPanel();
        jLabelMatriculaConsulta = new javax.swing.JLabel();
        jTextMatriculaConsulta = new javax.swing.JTextField();
        jButtonConsulta = new javax.swing.JButton();
        jLabelNomeConsulta = new javax.swing.JLabel();
        jLabelEmailConsulta = new javax.swing.JLabel();
        jTextFieldEmailConsulta = new javax.swing.JTextField();
        jTextFieldNomeConsulta = new javax.swing.JTextField();
        imagemIfpbConsulta = new javax.swing.JLabel();
        jPanelAtualizacao = new javax.swing.JPanel();
        imagemIfpbAtualizacao = new javax.swing.JLabel();
        jLabelMatriculaConsultaAtualizacao = new javax.swing.JLabel();
        jTextFieldMatriculaConsultaAtualizacao = new javax.swing.JTextField();
        jButtonConsultaAtualizacao = new javax.swing.JButton();
        jLabelNomeConsultaAtualizacao = new javax.swing.JLabel();
        jTextFieldNomeConsultaAtualizacao = new javax.swing.JTextField();
        jTextFieldEmailConsultaAtualizacao = new javax.swing.JTextField();
        jLabelEmailConsultaAtualizacao = new javax.swing.JLabel();
        jButtonSalvarAtualizacao = new javax.swing.JButton();
        jPanelRemocao = new javax.swing.JPanel();
        imagemIfpbRemocao = new javax.swing.JLabel();
        jLabelMatriculaRemocao = new javax.swing.JLabel();
        jLabelNomeRemocao = new javax.swing.JLabel();
        jLabelEmailRemocao = new javax.swing.JLabel();
        jTextFieldMatriculaRemocao = new javax.swing.JTextField();
        jButtonConsultaRemocao = new javax.swing.JButton();
        jButtonRemocao = new javax.swing.JButton();
        jTextFieldNomeRemocao = new javax.swing.JTextField();
        jTextFieldEmailRemocao = new javax.swing.JTextField();
        jPanelListagem = new javax.swing.JPanel();
        imagemIfpbListagem = new javax.swing.JLabel();
        jScrollPaneListagem = new javax.swing.JScrollPane();
        jListAlunos = new javax.swing.JList();
        jButtonListar = new javax.swing.JButton();
        jPanelSobre = new javax.swing.JPanel();
        jLabelCriadoSobre = new javax.swing.JLabel();
        jLabelContatoSobre = new javax.swing.JLabel();
        imagemIfpbSobre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Sistema Cadastro de Alunos");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        setForeground(java.awt.Color.white);
        setIconImage(imagemTitulo);
        setLocationByPlatform(true);
        setName("framePrincipal"); // NOI18N
        setResizable(false);

        abasSistemaCadastro.setPreferredSize(new java.awt.Dimension(500, 411));

        jPanelCadastroDeAluno.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCadastroDeAluno.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Alunos"));
        jPanelCadastroDeAluno.setPreferredSize(new java.awt.Dimension(500, 386));

        jLabelNomeCadastro.setText("Nome:");

        jLabelMatriculaCadastro.setText("Matrícula:");

        jLabelEmailCadastro.setText("E-Mail:");

        jButtonSalvarCadastro.setText("Salvar");
        jButtonSalvarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarCadastroActionPerformed(evt);
            }
        });

        jButtonLimparCadastro.setText("Limpar");
        jButtonLimparCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparCadastroActionPerformed(evt);
            }
        });

        imagemIfpbCadastro.setForeground(new java.awt.Color(255, 255, 255));
        imagemIfpbCadastro.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        imagemIfpbCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivos/INSTITUTO_GERAL.JPG"))); // NOI18N

        javax.swing.GroupLayout jPanelCadastroDeAlunoLayout = new javax.swing.GroupLayout(jPanelCadastroDeAluno);
        jPanelCadastroDeAluno.setLayout(jPanelCadastroDeAlunoLayout);
        jPanelCadastroDeAlunoLayout.setHorizontalGroup(
            jPanelCadastroDeAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroDeAlunoLayout.createSequentialGroup()
                .addGroup(jPanelCadastroDeAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroDeAlunoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelCadastroDeAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelCadastroDeAlunoLayout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addComponent(jButtonSalvarCadastro)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonLimparCadastro)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanelCadastroDeAlunoLayout.createSequentialGroup()
                                .addGap(0, 40, Short.MAX_VALUE)
                                .addGroup(jPanelCadastroDeAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanelCadastroDeAlunoLayout.createSequentialGroup()
                                        .addComponent(jLabelNomeCadastro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelCadastroDeAlunoLayout.createSequentialGroup()
                                        .addComponent(jLabelMatriculaCadastro)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelCadastroDeAlunoLayout.createSequentialGroup()
                                        .addComponent(jLabelEmailCadastro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanelCadastroDeAlunoLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(imagemIfpbCadastro)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanelCadastroDeAlunoLayout.setVerticalGroup(
            jPanelCadastroDeAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroDeAlunoLayout.createSequentialGroup()
                .addComponent(imagemIfpbCadastro)
                .addGap(33, 33, 33)
                .addGroup(jPanelCadastroDeAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeCadastro)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroDeAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmailCadastro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroDeAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMatriculaCadastro)
                    .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroDeAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvarCadastro)
                    .addComponent(jButtonLimparCadastro))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        abasSistemaCadastro.addTab("Cadastro", jPanelCadastroDeAluno);

        jPanelConsulta.setBackground(new java.awt.Color(255, 255, 255));
        jPanelConsulta.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta de Alunos"));
        jPanelConsulta.setPreferredSize(new java.awt.Dimension(500, 386));

        jLabelMatriculaConsulta.setText("Matrícula:");

        jButtonConsulta.setText("Consultar");
        jButtonConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaActionPerformed(evt);
            }
        });

        jLabelNomeConsulta.setText("Nome:");

        jLabelEmailConsulta.setText("E-Mail:");

        imagemIfpbConsulta.setForeground(new java.awt.Color(255, 255, 255));
        imagemIfpbConsulta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagemIfpbConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivos/INSTITUTO_GERAL.JPG"))); // NOI18N

        javax.swing.GroupLayout jPanelConsultaLayout = new javax.swing.GroupLayout(jPanelConsulta);
        jPanelConsulta.setLayout(jPanelConsultaLayout);
        jPanelConsultaLayout.setHorizontalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConsultaLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMatriculaConsulta)
                            .addComponent(jLabelNomeConsulta)
                            .addComponent(jLabelEmailConsulta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNomeConsulta)
                            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                                .addComponent(jTextMatriculaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonConsulta))
                            .addComponent(jTextFieldEmailConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelConsultaLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(imagemIfpbConsulta)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanelConsultaLayout.setVerticalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                .addComponent(imagemIfpbConsulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextMatriculaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsulta)
                    .addComponent(jLabelMatriculaConsulta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeConsulta)
                    .addComponent(jTextFieldNomeConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmailConsulta)
                    .addComponent(jTextFieldEmailConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );

        abasSistemaCadastro.addTab("Consulta", jPanelConsulta);

        jPanelAtualizacao.setBackground(new java.awt.Color(255, 255, 255));
        jPanelAtualizacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Atualização de Alunos"));

        imagemIfpbAtualizacao.setForeground(new java.awt.Color(255, 255, 255));
        imagemIfpbAtualizacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagemIfpbAtualizacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivos/INSTITUTO_GERAL.JPG"))); // NOI18N

        jLabelMatriculaConsultaAtualizacao.setText("Matrícula:");

        jButtonConsultaAtualizacao.setText("Consultar");
        jButtonConsultaAtualizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaAtualizacaoActionPerformed(evt);
            }
        });

        jLabelNomeConsultaAtualizacao.setText("Nome:");

        jLabelEmailConsultaAtualizacao.setText("E-Mail:");

        jButtonSalvarAtualizacao.setText("Atualizar");
        jButtonSalvarAtualizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarAtualizacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAtualizacaoLayout = new javax.swing.GroupLayout(jPanelAtualizacao);
        jPanelAtualizacao.setLayout(jPanelAtualizacaoLayout);
        jPanelAtualizacaoLayout.setHorizontalGroup(
            jPanelAtualizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAtualizacaoLayout.createSequentialGroup()
                .addGroup(jPanelAtualizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAtualizacaoLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(imagemIfpbAtualizacao))
                    .addGroup(jPanelAtualizacaoLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanelAtualizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMatriculaConsultaAtualizacao)
                            .addComponent(jLabelNomeConsultaAtualizacao)
                            .addComponent(jLabelEmailConsultaAtualizacao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelAtualizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNomeConsultaAtualizacao)
                            .addGroup(jPanelAtualizacaoLayout.createSequentialGroup()
                                .addComponent(jTextFieldMatriculaConsultaAtualizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonConsultaAtualizacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSalvarAtualizacao))
                            .addComponent(jTextFieldEmailConsultaAtualizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanelAtualizacaoLayout.setVerticalGroup(
            jPanelAtualizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAtualizacaoLayout.createSequentialGroup()
                .addComponent(imagemIfpbAtualizacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanelAtualizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMatriculaConsultaAtualizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsultaAtualizacao)
                    .addComponent(jLabelMatriculaConsultaAtualizacao)
                    .addComponent(jButtonSalvarAtualizacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAtualizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeConsultaAtualizacao)
                    .addComponent(jTextFieldNomeConsultaAtualizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanelAtualizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmailConsultaAtualizacao)
                    .addComponent(jTextFieldEmailConsultaAtualizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );

        abasSistemaCadastro.addTab("Atualização", jPanelAtualizacao);

        jPanelRemocao.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRemocao.setBorder(javax.swing.BorderFactory.createTitledBorder("Remoção de Alunos"));

        imagemIfpbRemocao.setForeground(new java.awt.Color(255, 255, 255));
        imagemIfpbRemocao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagemIfpbRemocao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivos/INSTITUTO_GERAL.JPG"))); // NOI18N

        jLabelMatriculaRemocao.setText("Matrícula:");

        jLabelNomeRemocao.setText("Nome:");

        jLabelEmailRemocao.setText("E-Mail:");

        jButtonConsultaRemocao.setText("Consultar");
        jButtonConsultaRemocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaRemocaoActionPerformed(evt);
            }
        });

        jButtonRemocao.setText("Remover");
        jButtonRemocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemocaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRemocaoLayout = new javax.swing.GroupLayout(jPanelRemocao);
        jPanelRemocao.setLayout(jPanelRemocaoLayout);
        jPanelRemocaoLayout.setHorizontalGroup(
            jPanelRemocaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRemocaoLayout.createSequentialGroup()
                .addGroup(jPanelRemocaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRemocaoLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(imagemIfpbRemocao))
                    .addGroup(jPanelRemocaoLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanelRemocaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMatriculaRemocao)
                            .addComponent(jLabelNomeRemocao)
                            .addComponent(jLabelEmailRemocao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelRemocaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNomeRemocao)
                            .addGroup(jPanelRemocaoLayout.createSequentialGroup()
                                .addComponent(jTextFieldMatriculaRemocao, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonConsultaRemocao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonRemocao))
                            .addComponent(jTextFieldEmailRemocao, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanelRemocaoLayout.setVerticalGroup(
            jPanelRemocaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRemocaoLayout.createSequentialGroup()
                .addComponent(imagemIfpbRemocao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPanelRemocaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMatriculaRemocao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsultaRemocao)
                    .addComponent(jLabelMatriculaRemocao)
                    .addComponent(jButtonRemocao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRemocaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeRemocao)
                    .addComponent(jTextFieldNomeRemocao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanelRemocaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmailRemocao)
                    .addComponent(jTextFieldEmailRemocao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );

        abasSistemaCadastro.addTab("Remoção", jPanelRemocao);

        jPanelListagem.setBackground(new java.awt.Color(255, 255, 255));
        jPanelListagem.setBorder(javax.swing.BorderFactory.createTitledBorder("Listagem de Alunos"));

        imagemIfpbListagem.setForeground(new java.awt.Color(255, 255, 255));
        imagemIfpbListagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagemIfpbListagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivos/INSTITUTO_GERAL.JPG"))); // NOI18N

        jListAlunos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jListAlunos.setSelectionBackground(new java.awt.Color(0, 153, 0));
        jScrollPaneListagem.setViewportView(jListAlunos);

        jButtonListar.setText("Listar");
        jButtonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelListagemLayout = new javax.swing.GroupLayout(jPanelListagem);
        jPanelListagem.setLayout(jPanelListagemLayout);
        jPanelListagemLayout.setHorizontalGroup(
            jPanelListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListagemLayout.createSequentialGroup()
                .addGroup(jPanelListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelListagemLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(imagemIfpbListagem))
                    .addGroup(jPanelListagemLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPaneListagem, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelListagemLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jButtonListar)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanelListagemLayout.setVerticalGroup(
            jPanelListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListagemLayout.createSequentialGroup()
                .addComponent(imagemIfpbListagem)
                .addGap(11, 11, 11)
                .addComponent(jScrollPaneListagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonListar)
                .addGap(0, 60, Short.MAX_VALUE))
        );

        abasSistemaCadastro.addTab("Listagem", jPanelListagem);

        jPanelSobre.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSobre.setBorder(javax.swing.BorderFactory.createTitledBorder("Sobre o Autor"));

        jLabelCriadoSobre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCriadoSobre.setText("Criado por: Vagner Barbosa");

        jLabelContatoSobre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelContatoSobre.setText("Contato: contato@vagnerbarbosa.com");

        imagemIfpbSobre.setForeground(new java.awt.Color(255, 255, 255));
        imagemIfpbSobre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagemIfpbSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivos/INSTITUTO_GERAL.JPG"))); // NOI18N

        javax.swing.GroupLayout jPanelSobreLayout = new javax.swing.GroupLayout(jPanelSobre);
        jPanelSobre.setLayout(jPanelSobreLayout);
        jPanelSobreLayout.setHorizontalGroup(
            jPanelSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSobreLayout.createSequentialGroup()
                .addGroup(jPanelSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSobreLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(imagemIfpbSobre, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSobreLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabelCriadoSobre))
                    .addGroup(jPanelSobreLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabelContatoSobre)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanelSobreLayout.setVerticalGroup(
            jPanelSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSobreLayout.createSequentialGroup()
                .addComponent(imagemIfpbSobre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabelCriadoSobre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelContatoSobre)
                .addGap(139, 139, 139))
        );

        abasSistemaCadastro.addTab("Sobre", jPanelSobre);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abasSistemaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(abasSistemaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        abasSistemaCadastro.getAccessibleContext().setAccessibleName("Cadastro");
        abasSistemaCadastro.getAccessibleContext().setAccessibleDescription("?");

        setSize(new java.awt.Dimension(503, 457));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
        private Aluno aluno = new Aluno();       


    private void jButtonSalvarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarCadastroActionPerformed
          if ("".equals(jTextFieldNome.getText()) || "".equals(jTextFieldEmail.getText()) || "".equals(jTextFieldMatricula.getText())) {
                JOptionPane.showMessageDialog(null,"É preciso preencher todos os campos!");
            } else {
            aluno.setNome(jTextFieldNome.getText());
            aluno.setEmail(jTextFieldEmail.getText());
            aluno.setMatricula(jTextFieldMatricula.getText().toUpperCase()); 
            ODB odb = null;
            odb = ODBFactory.open("banco.neodatis");
            odb.store(aluno);
            odb.close();            
            JOptionPane.showMessageDialog(null,"Cadastro realizado com sucesso");            
            jTextFieldNome.setText("");
            jTextFieldEmail.setText("");
            jTextFieldMatricula.setText("");            
            }
        
    }//GEN-LAST:event_jButtonSalvarCadastroActionPerformed
     
    private void jButtonLimparCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparCadastroActionPerformed
        jTextFieldNome.setText("");
        jTextFieldMatricula.setText("");
        jTextFieldEmail.setText("");
    }//GEN-LAST:event_jButtonLimparCadastroActionPerformed

    private void jButtonConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaActionPerformed
 
            ODB odb = null;
            odb = ODBFactory.open("banco.neodatis");

            Aluno aluno = new Aluno();
            IQuery query = new CriteriaQuery(Aluno.class, Where.equal("matricula", jTextMatriculaConsulta.getText().toUpperCase()));
            Aluno alunoConsulta;            
            alunoConsulta = (Aluno) odb.getObjects(query).getFirst();
            odb.close();
            if (alunoConsulta.getNome() == null) {
            jTextMatriculaConsulta.setBackground(Color.red);    
            JOptionPane.showMessageDialog(null,"Matrícula não existe!");
            jTextMatriculaConsulta.setBackground(Color.white);
            } else {
            jTextMatriculaConsulta.setText(alunoConsulta.getMatricula());            
            jTextMatriculaConsulta.setBackground(Color.green);
            jTextFieldNomeConsulta.setText(alunoConsulta.getNome());            
            jTextFieldEmailConsulta.setText(alunoConsulta.getEmail());            
            }           
              
    }//GEN-LAST:event_jButtonConsultaActionPerformed

    private void jButtonConsultaAtualizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaAtualizacaoActionPerformed

            ODB odb = null;
            odb = ODBFactory.open("banco.neodatis");

            Aluno aluno = new Aluno();
            IQuery query = new CriteriaQuery(Aluno.class, Where.equal("matricula", jTextFieldMatriculaConsultaAtualizacao.getText().toUpperCase()));
            Aluno alunoConsulta;
            
            alunoConsulta = (Aluno) odb.getObjects(query).getFirst();
            odb.close();
            if (alunoConsulta.getNome() == null) {
            jTextFieldMatriculaConsultaAtualizacao.setBackground(Color.red);
            JOptionPane.showMessageDialog(null,"Matrícula não existe!");
            jTextFieldNomeConsultaAtualizacao.setText("");
            jTextFieldMatriculaConsultaAtualizacao.setText("");
            jTextFieldEmailConsultaAtualizacao.setText("");
            jTextFieldMatriculaConsultaAtualizacao.setBackground(Color.white);           
            } else {
            jTextFieldMatriculaConsultaAtualizacao.setText(alunoConsulta.getMatricula());
            jTextFieldMatriculaConsultaAtualizacao.setEditable(false);
            jTextFieldMatriculaConsultaAtualizacao.setBackground(Color.green);
            jTextFieldNomeConsultaAtualizacao.setText(alunoConsulta.getNome());
            jTextFieldEmailConsultaAtualizacao.setText(alunoConsulta.getEmail());            
            }           
    }//GEN-LAST:event_jButtonConsultaAtualizacaoActionPerformed

    private void jButtonSalvarAtualizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarAtualizacaoActionPerformed
        
            ODB odb = null;
            odb = ODBFactory.open("banco.neodatis");

            Aluno aluno = new Aluno();
            IQuery query = new CriteriaQuery(Aluno.class, Where.equal("matricula", jTextFieldMatriculaConsultaAtualizacao.getText().toUpperCase()));
            Aluno alunoConsulta;
            
            alunoConsulta = (Aluno) odb.getObjects(query).getFirst();
            Aluno a = alunoConsulta; 
            odb.delete(alunoConsulta);
            odb.close();
            if (alunoConsulta == null) {
            jTextFieldMatriculaConsultaAtualizacao.setBackground(Color.red);
            JOptionPane.showMessageDialog(null,"Matrícula não existe!");
            jTextFieldMatriculaConsultaAtualizacao.setEditable(true);
            jTextFieldNomeConsultaAtualizacao.setText("");
            jTextFieldMatriculaConsultaAtualizacao.setText("");
            jTextFieldEmailConsultaAtualizacao.setText("");
            jTextFieldMatriculaConsultaAtualizacao.setBackground(Color.white);
            }
            if ("".equals(jTextFieldEmailConsultaAtualizacao.getText()) || "".equals(jTextFieldMatriculaConsultaAtualizacao.getText()) || "".equals(jTextFieldMatriculaConsultaAtualizacao.getText())) {
            JOptionPane.showMessageDialog(null,"É preciso consultar um Aluno válido antes de atualizar!");
            } 
            else {                
                a.setNome(jTextFieldNomeConsultaAtualizacao.getText());
                a.setEmail(jTextFieldEmailConsultaAtualizacao.getText());               
                odb = ODBFactory.open("banco.neodatis");
                odb.store(a);
                odb.close();  
                JOptionPane.showMessageDialog(null,"Cadastro atualizado com sucesso");
                jTextFieldMatriculaConsultaAtualizacao.setEditable(true);
                jTextFieldNomeConsultaAtualizacao.setText("");
                jTextFieldMatriculaConsultaAtualizacao.setText("");
                jTextFieldEmailConsultaAtualizacao.setText("");
                jTextFieldMatriculaConsultaAtualizacao.setBackground(Color.white);
            }          
   
    }//GEN-LAST:event_jButtonSalvarAtualizacaoActionPerformed

    private void jButtonConsultaRemocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaRemocaoActionPerformed

            ODB odb = null;
            odb = ODBFactory.open("banco.neodatis");

            Aluno aluno = new Aluno();
            IQuery query = new CriteriaQuery(Aluno.class, Where.equal("matricula", jTextFieldMatriculaRemocao.getText().toUpperCase()));
            Aluno alunoConsulta;
            
            alunoConsulta = (Aluno) odb.getObjects(query).getFirst();
            odb.close();
            if (alunoConsulta.getNome() == null) {
            jTextFieldMatriculaRemocao.setBackground(Color.red);
            JOptionPane.showMessageDialog(null,"Matrícula não existe!");
            jTextFieldNomeRemocao.setText("");
            jTextFieldMatriculaRemocao.setText("");
            jTextFieldEmailRemocao.setText("");
            jTextFieldMatriculaRemocao.setBackground(Color.white);            
            } else {
            jTextFieldMatriculaRemocao.setText(alunoConsulta.getMatricula());            
            jTextFieldMatriculaRemocao.setEditable(false);
            jTextFieldMatriculaRemocao.setBackground(Color.green);
            jTextFieldNomeRemocao.setText(alunoConsulta.getNome());
            jTextFieldEmailRemocao.setText(alunoConsulta.getEmail());            
            }
            

    }//GEN-LAST:event_jButtonConsultaRemocaoActionPerformed

    private void jButtonRemocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemocaoActionPerformed
        
            ODB odb = null;
            odb = ODBFactory.open("banco.neodatis");

            Aluno aluno = new Aluno();
            IQuery query = new CriteriaQuery(Aluno.class, Where.equal("matricula", jTextFieldMatriculaRemocao.getText().toUpperCase()));
            Aluno alunoConsulta;
            
            alunoConsulta = (Aluno) odb.getObjects(query).getFirst();

            if (alunoConsulta.getNome() == null) {
            jTextFieldMatriculaRemocao.setBackground(Color.red);
            JOptionPane.showMessageDialog(null,"Matrícula não existe!");
            jTextFieldMatriculaRemocao.setEditable(true);                
            jTextFieldNomeRemocao.setText("");
            jTextFieldMatriculaRemocao.setText("");
            jTextFieldEmailRemocao.setText("");
            jTextFieldMatriculaRemocao.setBackground(Color.white);            
            }
            if ("".equals(jTextFieldEmailRemocao.getText()) || "".equals(jTextFieldMatriculaRemocao.getText()) || "".equals(jTextFieldNomeRemocao.getText())) {
            JOptionPane.showMessageDialog(null,"É preciso consultar um Aluno válido antes de remover!");
            } 
            else {                
                alunoConsulta.setNome(jTextFieldNomeRemocao.getText());
                alunoConsulta.setEmail(jTextFieldEmailRemocao.getText());                
                odb.delete(alunoConsulta);
                odb.close();

                JOptionPane.showMessageDialog(null,"Aluno removido com sucesso!");
                jTextFieldMatriculaRemocao.setEditable(true);                
                jTextFieldNomeRemocao.setText("");
                jTextFieldMatriculaRemocao.setText("");
                jTextFieldEmailRemocao.setText("");
                jTextFieldMatriculaRemocao.setBackground(Color.white);
            }            
   
    }//GEN-LAST:event_jButtonRemocaoActionPerformed

    private void jButtonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarActionPerformed
        

            ODB odb = null;
            odb = ODBFactory.open("banco.neodatis");
            Objects<Aluno> alunos = odb.getObjects(Aluno.class);
            Vector al = new Vector();
            while (alunos.hasNext()) {
            al.add(alunos.next());
            }
            jListAlunos.setListData(al);
       
            odb.close();
    }//GEN-LAST:event_jButtonListarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {        
        
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new GUICadastro().setVisible(true);
            }
        });          
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane abasSistemaCadastro;
    private javax.swing.JLabel imagemIfpbAtualizacao;
    private javax.swing.JLabel imagemIfpbCadastro;
    private javax.swing.JLabel imagemIfpbConsulta;
    private javax.swing.JLabel imagemIfpbListagem;
    private javax.swing.JLabel imagemIfpbRemocao;
    private javax.swing.JLabel imagemIfpbSobre;
    private javax.swing.JButton jButtonConsulta;
    private javax.swing.JButton jButtonConsultaAtualizacao;
    private javax.swing.JButton jButtonConsultaRemocao;
    private javax.swing.JButton jButtonLimparCadastro;
    private javax.swing.JButton jButtonListar;
    private javax.swing.JButton jButtonRemocao;
    private javax.swing.JButton jButtonSalvarAtualizacao;
    private javax.swing.JButton jButtonSalvarCadastro;
    private javax.swing.JLabel jLabelContatoSobre;
    private javax.swing.JLabel jLabelCriadoSobre;
    private javax.swing.JLabel jLabelEmailCadastro;
    private javax.swing.JLabel jLabelEmailConsulta;
    private javax.swing.JLabel jLabelEmailConsultaAtualizacao;
    private javax.swing.JLabel jLabelEmailRemocao;
    private javax.swing.JLabel jLabelMatriculaCadastro;
    private javax.swing.JLabel jLabelMatriculaConsulta;
    private javax.swing.JLabel jLabelMatriculaConsultaAtualizacao;
    private javax.swing.JLabel jLabelMatriculaRemocao;
    private javax.swing.JLabel jLabelNomeCadastro;
    private javax.swing.JLabel jLabelNomeConsulta;
    private javax.swing.JLabel jLabelNomeConsultaAtualizacao;
    private javax.swing.JLabel jLabelNomeRemocao;
    private javax.swing.JList jListAlunos;
    private javax.swing.JPanel jPanelAtualizacao;
    private javax.swing.JPanel jPanelCadastroDeAluno;
    private javax.swing.JPanel jPanelConsulta;
    private javax.swing.JPanel jPanelListagem;
    private javax.swing.JPanel jPanelRemocao;
    private javax.swing.JPanel jPanelSobre;
    private javax.swing.JScrollPane jScrollPaneListagem;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEmailConsulta;
    private javax.swing.JTextField jTextFieldEmailConsultaAtualizacao;
    private javax.swing.JTextField jTextFieldEmailRemocao;
    private javax.swing.JTextField jTextFieldMatricula;
    private javax.swing.JTextField jTextFieldMatriculaConsultaAtualizacao;
    private javax.swing.JTextField jTextFieldMatriculaRemocao;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNomeConsulta;
    private javax.swing.JTextField jTextFieldNomeConsultaAtualizacao;
    private javax.swing.JTextField jTextFieldNomeRemocao;
    private javax.swing.JTextField jTextMatriculaConsulta;
    // End of variables declaration//GEN-END:variables

}
